#datasource
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#dubbo
dubbo:
  application:
    name: servicedemo
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  monitor:
    protocol: regiter

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhku.mh.servicedemo.entities

#showSql
logging:
  level:
    com:
      example:
        mapper : debug